### PR TITLE
Consolidate install and helper scripts into one version each

### PR DESCRIPTION
**Pull request by sts10**
In an effort to reduce the amount of repeated code in Blackbox (and thus more code to maintain), I've endeavored to consolidate `v1/install.sh` and `v2/install.sh` into simply `install.sh` and likewise consolidate `v1/helper.sh` and `v2/helper.sh` into `helper.sh`. 

The way I made this work is that both the new `helper.sh` and the new `install.sh` **accept an argument when called**, either `1` or `2`, based on the e-ink display version the user is using. For example, to install for version 1, we now do:

```bash
ExecStart=/home/hush/blackbox/install.sh 1
```

(Obviously, a function to _detect_ the version for them would be better...) 

The new scripts then take action based on the inputted parameter. We call this first given parameter with `$1`. So as a generic example:

```bash
if [ $1 == "1" ]; then
    # do what's needed for v 1
elif [ $1 == "2" ]; then
    # do what's needed for v 2
fi
```

I haven't tested this at all! I don't know if the `cat`ing of the Python still works in this version! But I think this is a push in the right direction re: removing repeated code!

### CODE REVIEW

**Comment by sts10** [comment]
Now have a feeling I'm missing something big here... 

When we `git clone https://github.com/scidsg/hushline.git` in the helper.sh script... where/when/how do we use files from that repo? Does it need to know what version of the e-ink screen the user has?

**Comment by glenn-sorrentino** [comment]
The Hush Line repo is the app. Our current install.sh is a modified intall-tor-only.sh from Hush Line. Blackbox includes the steps for the web interface for the email and pgp information. We aren't including that in Hush Line because we don't want to send data over http to a VPS.

**Comment by sts10** [comment]
Sorry, my question is basically: Is this blackbox repo **self-sufficient**, or does it rely on code files that exist only in the Hush Line repo (`https://github.com/scidsg/hushline`)? 

Another way to ask: what would happen if we removed the line `git clone https://github.com/scidsg/hushline.git` from the Blackbox helper scripts? Would Blackbox still run/work?

**Comment by glenn-sorrentino** [comment]
No it wouldn’t - the Hush Line repo contains app.py, the template files, requirements, etc. 

The SOT should be the Hush Line repo. Blackbox is just an alternative no-terminal installation method for Pi + e-paper display-only deployments.

**Comment by sts10** [comment]
Ah, thanks for the clarification. 

And I think I see now at least [one place](https://github.com/scidsg/blackbox/blob/main/v2/install.sh#L44-L55) where the Blackbox code relies on the Hush Line code.

All that said, I'm still curious if the changes made in this PR would work.

**Comment by sts10** [comment]
So to install, we'd now have to specify the e-ink display version with the `bash` command's `-s` flag:
For v2
```
curl -sSL https://raw.githubusercontent.com/scidsg/blackbox/main/helper.sh | sudo bash -s 2
```

For v1:
```
curl -sSL https://raw.githubusercontent.com/scidsg/blackbox/main/helper.sh | sudo bash -s 1
```

Note that we could make v2 the default, such that if no argument is given, it just assumes v2.

**Comment by sts10** [comment]
If we're ending support for Waveshare e-paper diplay Rev2.1, this PR isn't really relevant any more.

**Pull request closed without merging**
